BlackFly/urls.py
from django.conf.urls import include, url, patterns
import posts.views
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from django.core.urlresolvers import reverse
from django.views.generic.edit import CreateView
from django.views.generic.base import RedirectView

from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

urlpatterns = patterns(" ", 
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', auth_views.login, {'template_name': 'posts/login.html'}, name="login"),
    url(r'^logout/$', auth_views.logout, {'template_name': 'posts/logged_out.html'}, name="logout"),
    url(r'^register/$', posts.views.register, name="register"),
    url(r'^blog/$', login_required(posts.views.ListPostView.as_view()), name="post-list"),
    url(r'^blog/(?P<pk>\d+)/$', login_required(posts.views.PostView.as_view()), name="post-detail"),
    url(r'^blog/new/$', login_required(posts.views.CreatePostView.as_view()), name="post-new"),
    url(r'^blog/(?P<pk>\d+)/modify/$', login_required(posts.views.UpdatePostView.as_view()), name="post-modify"),
    url(r'^blog/(?P<pk>\d+)/delete/$', login_required(posts.views.DeletePostView.as_view()), name="post-delete"),
    url(r'^blog/(?P<post_id>[0-9]+)/comments/$', posts.views.addComment, name="postComment"),
    url(r'^comments(?P<comment_id>[0-9]+)/reply/$', posts.views.addComment, name="reply"),
    url(r'^comments(?P<comment_id>[0-9]+)/modifycomment/$', posts.views.modifyComment, name="modifyComment"),
    url(r'^comments(?P<comment_id>[0-9]+)/deletecomment/$', posts.views.deleteComment, name="deleteComment"),
)


urlpatterns += staticfiles_urlpatterns()

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User)
    title = models.CharField(max_length=100)
    body = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    modified_date = models.DateTimeField('date modified', auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.id})


class Comment(models.Model):
    author = models.ForeignKey(User)
    body = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    modified_date = models.DateTimeField('date modified', auto_now=True)

    def __str__(self):
        return self.body


class PostComment(models.Model):
    post = models.ForeignKey(Post)
    comment = models.ForeignKey(Comment)
    pub_date = models.DateTimeField('post published', auto_now_add=True)


class Reply(models.Model):
    reply = models.ForeignKey(Comment, related_name='parent_comments')
    comment = models.ForeignKey(Comment, related_name='replies')
    pub_date = models.DateTimeField('date posted', auto_now_add=True)

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic
#from .models import Post, Comment, PostComment, Reply
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect("/login/")
    else:
        form = UserCreationForm()
    return render(request, "accounts/register.html", {
        'form': form,
    })

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
# Create your views here.
from django.views import generic
from django.core.urlresolvers import reverse
from .models import Post, Comment, PostComment, Reply
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist

class PostOwnerMixin(object):

	def get_object(self, queryset=None):
		""" Returns the object the view is displaying.
		"""
		if queryset is None:
			queryset = self.get_queryset()

		pk = self.kwargs.get(self.pk_url_kwarg, None)
		queryset = queryset.filter(pk=pk, author=self.request.user,)

		try:
			obj = queryset.get()
		except ObjectDoesNotExist:
			raise PermissionDenied

		return obj

class ListPostView(generic.ListView):

	model = Post
	template_name = 'posts/post_list.html'
	context_object_name = 'latest_blog_posts'

	def get_queryset(self):
		return Post.objects.order_by('-pub_date')

class CreatePostView(generic.CreateView):

	model = Post
	template_name = 'posts/new_post.html'
	fields = ('title', 'body')

	def get_success_url(self):
		return reverse('post-list')

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super(CreatePostView, self).form_valid(form)

class PostView(generic.DetailView):

	model = Post
	template_name = 'posts/post.html'
	fields = ('__all__')

class UpdatePostView(PostOwnerMixin, generic.UpdateView):

	model = Post
	template_name = 'posts/post_modify.html'
	fields = ('title', 'body')

	def get_absolute_url(self):
		return reverse('posts/post-detail', kwargs={'pk': self.pk})

class DeletePostView(PostOwnerMixin, generic.DeleteView):

	model = Post
	template_name = 'posts/delete_post.html'

	def get_success_url(self):
		return reverse('post-list')

@login_required
def addComment(request, post_id=None, comment_id=None):
	
	next = getNextUrl(request)
	
	if (request.method != 'POST'):
		raise Http404();

	new_comment = Comment.objects.create(author=request.user, body=request.POST['body'])
	
	if (post_id):
		# add comment to post
		post = get_object_or_404(Post, pk=post_id)
		PostComment.objects.create(post=post, comment=new_comment)

	elif (comment_id):
		# add reply to comment
		comment = get_object_or_404(Comment, pk=comment_id)
		Reply.objects.create(comment=comment, reply=new_comment)
	return redirect(next)

@login_required
def modifyComment(request, comment_id):
	next = getNextUrl(request)
	comment = get_object_or_404(Comment, pk=comment_id)
	checkAuthor(request, comment)
	comment.body = request.POST['body']
	comment.save()
	return redirect(next)

@login_required
def deleteComment(request, comment_id):
	next = getNextUrl(request)
	comment = get_object_or_404(Comment, pk=comment_id)
	checkAuthor(request, comment)
	comment.delete()
	return redirect(next)

def checkAuthor(request, obj):
	if(request.user.id != obj.author.id):
		raise Http404('You are not authorized to perform this act')

def getNextUrl(request):
	''' Gets the url specified by 'next' GET parameter; uses default otherwise '''
	try:
		next = request.GET['next']
	except KeyError:
		return reverse('post-list')
	return next;

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect("/login/")
    else:
        form = UserCreationForm()
    return render(request, "posts/register.html", {
        'form': form,
    })

accounts/templates/accounts/base.html
{% load staticfiles %}
<html>
<head>
  <link href="{% static 'posts/bootstrap-3.3.5-dist/css/bootstrap.min.css' %}"
  		rel="stylesheet" media="screen">
</head>
<body>

	<div>
		{{ user }}
		{% if user.is_anonymous %}
		<a href="{% url 'django.contrib.auth.views.login' %}">Login</a>
		{% else %}
		<a href="{% url 'django.contrib.auth.views.logout' %}">Logout</a>
		{% endif %}
	</div>

{% block sidebar %}
{% endblock sidebar %}

{% block content %}
	
	
{% endblock content %}
	<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

{% block footer %}
{% endblock footer %}
</body>
</html>

accounts/templates/accounts/logged_out.html
{% extends "accounts/base.html" %}
{% block content %}

Logged out!

{% endblock %}

accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}
{% block content %}
<h2>Welcome to Contact Keeper. Please Login here</h2>
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="POST" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
	<td>{{ form.username.label_tag }}</td>
	<td>{{ form.username }}</td>
</tr>
<tr>
	<td>{{ form.password.label_tag }}</td>
	<td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

<a href="{% url "register" %}">New to us? Register here</a>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "accounts/base.html" %}

{% block title %}Create an account{% endblock %}

{% block content %}
  <h1>Create an account</h1>

<form action="" 
  	method="POST">{% csrf_token %}
  	  
      {{ form.as_p }}

      <input type="submit" value="Create the account">
  </form>
{% endblock %}

posts/templates/posts/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<link href="{% static 'posts/bootstrap-3.3.5-dist/css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
   	<script src="/scripts/jquery.min.js"></script>
   	<script src="/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
	<div>
		{{ user }}
		{% if user.is_anonymous %}
		<a href="{% url "login" %}">Login</a>
		{% else %}
		{% include 'posts/sidebar.html' %}
		{% endif %}
	</div>
	<div class="ui grid">
		<div class="three wide column"></div>
	<div id="main-content" class="nine wide column"></div>

{% block content %}
    
{% endblock %}
	</div>
</body>
</html>

posts/templates/posts/comment_list.html
<h3>Comments</h3>

<ul>
{% for comment in post.postcomment_set.all %}
		<li>
				{% include 'posts/show_comment.html' with comment=comment.comment %}
		</li>	
{% empty %}
		<li>No Comments</li>
{% endfor %}
</ul>

posts/templates/posts/comment_modify.html
<form role="form" class="editForm" action="{% url 'modifyComment' comment.id %}?next={% url 'post-detail' post.id %}" method="POST">
{% csrf_token %}

<div class="ui form">
	<p><div class="form-group">
		<textarea name="body" class="form-control" rows="3">{{ comment.body }}</textarea>
	</div></p>
	<button type="submit" class="btn btn-primary">Edit</button>
</div>
</form>

posts/templates/posts/delete_post.html
{% extends "posts/base.html" %}
{% block content %}

<h1>Delete Post</h1>

<p>Are you sure you want to delete the post?{{ post }}</p>

<form action="{% url "post-delete" pk=post.id %}" method="POST">
{% csrf_token %}
<input type="submit" value="Yes,Delete" />

<a href="{% url "post-detail" pk=post.id %}">No, cancel</a>
</form>

{% endblock %}

posts/templates/posts/logged_out.html
{% extends "posts/base.html" %}
{% block content %}

You are Logged out! Thanks for spending some quality time with us. Hope to see you soon!

{% endblock %}

posts/templates/posts/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head><title>login page</title>
		<link type="text/css" rel="stylesheet" href="{% static 'posts/login/body.css' %}" />
	</head>
<body class="body">
	<h1 id="header">Welcome to BlackFly Blogging App</h1>
	<p><h4>Please Login here to start BLOGGING. :-)</h4></p>
	{% if form.errors %}
	<p>Your username and password didn't match. Please try again.</p>
	{% endif %}

	<form method="POST" action="{% url "login" %}">
	{% csrf_token %}
	<table class="table">
	<tr>
		<td><input class="username" type="text" name="username" placeholder="Username" ></td>
	</tr>
	<tr>
		<td><input class="username" type="password" name="password" placeholder="Password"></td>
	</tr>
	</table>
	<p><input type="submit" value="Login" class="submit_button"/></p>
	<input type="hidden" name="next" value="{{ next }}" />
	</form>
	</p>
	<div><a href="{% url "register" %}">New to us? <br><span>Register here</span></a></div>

</body>
</html>

posts/templates/posts/new_comment.html
<h2>Post a Comment</h2>

<form role="form" action="{% url 'postComment' post.id %}?next={% url 'post-detail' post.id %}" method="POST">
{% csrf_token %}
<div class="ul_form">
	<div class="form-group">
		<textarea name="body" class="form-control" rows="5" ></textarea>
	</div>
	
</div>
<button type="submit" class="btn btn-primary">Submit</button>
</form>

posts/templates/posts/new_post.html
{% extends "posts/base.html" %}

{% block content %}

<form role="form" action="{{ action }}"  method="POST">
{% csrf_token %}
<div class="ul_form">
	<div class="form-group">
		<label for="name">Title</label>
		<input id="title" type="text" name="title" class="form-control">
	</div>
	<div class="form-group">
		<label for="name">Content</label>
		<textarea id="body" name="body" class="form-control" rows="10"></textarea>
	</div>
<button id="save_post" type="submit" class="btn btn-primary btn-lg">Post</button>
</div>
</form>

{% endblock %}

posts/templates/posts/post.html
{% extends "posts/base.html" %}

{% block content %}

<h1>{{ post.title }}</h1>
{% if user.id == post.author.id %}
<a href="{% url "post-modify" pk=post.id %}">Edit</a>
<a href="{% url "post-delete" pk=post.id %}">Delete</a>
{% endif %}
<p>{{ post.body }}</p>
{% include 'posts/comment_list.html' %}

{% include 'posts/new_comment.html' %}

{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/base.html" %}

{% block content %}

<h1>Recent Posts</h1>

{% if latest_blog_posts %}
<ul>
	{% for post in object_list %}
		<li class="post">
		<a href="{{ post.get_absolute_url }}">{{ post }}</a><br>
		By {{ post.author }} on {{ post.modified_date }}</br
		</li>
	{% endfor %}
</ul>
{% else %}
<p>No posts yet</p>
{% endif %}

{% endblock %}

posts/templates/posts/post_modify.html
{% extends "posts/base.html" %}

{% block content %}

<form role="form" action="{% url 'post-modify' post.id %}" method="POST">
{% csrf_token %}
<div class="ul_form">
	<div class="form-group">
		<label for="name">Title</label>
		<input id="title" type="text" name="title" value="{{ post.title }}"class="form-control">
	</div>
	<div class="form-group">
		<label for="name">Content</label>
		<textarea id="body" name="body" class="form-control" rows="10">{{ post.body }}</textarea>
	</div>
<button id="save_post" type="submit" class="btn btn-primary btn-lg">Edit</button>
</div>
</form>
{% endblock %}

posts/templates/posts/reply.html
<form role="form" class="replyForm" action="{% url 'reply' comment.id %}?next={% url 'post-detail' post.id %}" method="POST">
{% csrf_token %}

<div class="ui form">
	<div class="form-group">
		<label>Reply</label>
		<textarea name="body" class="form-control" rows="3"></textarea>
	</div>
	<div class="field">
		<button type="submit", class="btn btn-primary">Post Reply</button>
	</div>
</div>
</form>

posts/templates/posts/show_comment.html
{{ comment.body }} - {{ comment.author }}
<a href="", class="replyToggle">Reply</a>

{% if user.id == comment.author.id %}

{% include 'posts/comment_modify.html' %}
<a href="" class="editToggle">Edit</a>
<a href="{% url 'deleteComment' comment.id %}?next={% url 'post-detail' post.id %}">Delete</a>
{% endif %}
{% include 'posts/reply.html' %}
<ul>
{% for reply in comment.replies.all %}
	<li>
		{% include 'posts/show_comment.html' with comment=reply.reply %}
	</li>
{% endfor %}
</ul>

posts/templates/posts/sidebar.html
<div class="ui fixed vertical menu">
		<a class="item" href="{% url 'post-new' %}">Write New Post</a>
		<a class="item" href="{% url 'post-list' %}">Blog</a>
		<a class="item" href="{% url 'logout' %}">Logout</a>
</div>